// src/routes/topic/index.tsx

import { createSignal, onMount } from 'solid-js'
import { For, Show } from 'solid-js/web'
import TopicCard from '~/components/Topic/Card'
import { Topic } from '~/lib/graphql/types.gen'
import { useStore } from '~/store'
import './topics.scss'
export let update

let sortedKeys = []
let topicsGroupedByAlphabet = []

const groupBy = (arr) => {
  let firstLetter = null

  return arr.reduce(
    (acc, currentValue) => {
      let currentLetter = currentValue.title.slice(0, 1)

      if (/[a-zA-Z0-9]/.test(currentLetter)) {
        currentLetter = 'A-Z'
      } else if (!acc[currentLetter]) {
        firstLetter = currentLetter
        acc[firstLetter] = []
      }

      acc[currentLetter].push(currentValue)

      return acc
    },
    { 'A-Z': [] }
  )
}

export default () => {
  const store = useStore()
  const { topics, userTopics } = store[0]
  const [mode, setMode] = createSignal('views')
  const byMode = (a: Topic, b: Topic) => b.topicStat[mode()] - a.topicStat[mode()]

  const sortTopics = () => {
    if (mode() === 'alphabet') {
      topicsGroupedByAlphabet = groupBy(update.topicsAll.slice(0))
      sortedKeys = Object.keys(topicsGroupedByAlphabet).sort()
      sortedKeys.forEach((letter) => {
        topicsGroupedByAlphabet[letter] = topicsGroupedByAlphabet[letter].sort(
          // eslint-disable-next-line no-confusing-arrow
          (a, b) => ((a.title > b.title) ? 1 : (a.title < b.title) ? -1 : 0)
          )
        })
    }

    return Object.values(topics).sort(byMode)
  }

  onMount(sortTopics)

  return (
    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <h1>Темы</h1>
          <p>
            Подпишитесь на интересующие вас темы, чтобы настроить вашу персональную
            летну и моментально узнавать о новых публикациях и обсуждениях
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <ul class="view-switcher">
            <li classList={{ selected: mode() === 'views' }}>
              <a href="#views" onClick={() => setMode('views')}>По просмотрам</a>
            </li>
            <li classList={{ selected: mode() === 'shouts' }}>
              <a href="#shouts" onClick={() => setMode('shouts')}>По публикациям</a
              >
            </li>
            <li classList={{ selected: mode() === 'alphabet' }}>
              <a href="#alphabet" onClick={() => setMode('alphabet')}>По алфавиту</a>
            </li>
          </ul>

          <Show when={mode() === 'alphabet'} fallback={
            <div class="stats">
              <For each={Array.from(topics)}>
                {(topic: Topic) => (
                  <TopicCard topic={topic} compact={false} subscribed={userTopics?.includes(topic.slug)} />
                )}
              </For>
            </div>
          }>
            <For each={sortedKeys}>
              {letter => (
                <div class="group">
                  <h2>{letter}</h2>
                  <div class="container">
                    <div class="row">
                      <For each={topicsGroupedByAlphabet[letter]}>
                        {(topic: Topic) => (
                          <div class="topic col-3">
                            <div class="topic-title">
                              <a href="/topic/{topic.slug}">{topic.title}</a>
                            </div>
                          </div>
                        )}
                      </For>
                    </div>
                  </div>
                </div>
              )}
            </For>
          </Show>
        </div>
      </div>
    </div>
  )
}

// src/routes/topic/index.svelte
<script lang="ts" context="module">
	export const prerender = true
</script>

<script lang="ts">
	import { onMount } from 'svelte'
	import type { Topic } from '../../lib/codegen'
	import { topicslist } from '../../stores/zine'
	import TopicCard from '../../components/TopicCard.svelte'
	import { getSubscriptions } from '$lib/cookie';

	let topics: Partial<Topic>[]
	let mode = ''
	let sortedKeys = []
	let topicsGroupedByAlphabet = []

	let subscribedList = []

	const groupBy = (arr) => {
		let firstLetter = null
		return arr.reduce(
			(acc, currentValue) => {
				let currentLetter = currentValue.title.slice(0, 1)
				if (/[a-zA-Z0-9]/.test(currentLetter)) {
					currentLetter = 'A-Z'
				} else if (!acc[currentLetter]) {
					firstLetter = currentLetter
					acc[firstLetter] = []
				}
				acc[currentLetter].push(currentValue)
				return acc
			},
			{ 'A-Z': [] }
		)
	}

	$: if ($topicslist) {
		if (mode === 'alphabet') {
			topicsGroupedByAlphabet = groupBy(topics.slice(0))
			sortedKeys = Object.keys(topicsGroupedByAlphabet).sort()
			sortedKeys.forEach((letter) => {
				topicsGroupedByAlphabet[letter] = topicsGroupedByAlphabet[letter].sort(
					(a, b) => {
						if (a.title > b.title) {
							return 1
						} else if (a.title < b.title) {
							return -1
						}
						return 0
					}
				)
			})
		} else {
			topics = $topicslist.sort((a, b) => b.topicStat[mode] - a.topicStat[mode])
		}
	}

	const setMode = () => mode = window.location.hash.replace('#', '') || 'views'

	onMount(async () => {
		setMode()
		subscribedList = await getSubscriptions(document.cookie, 'topics')
	})
</script>

<svelte:window on:hashchange={setMode} />

<div class="container">
	<div class="row">
		<div class="col-md-9">
			<h1>Темы</h1>
			<p>
				Подпишитесь на интересующие вас темы, чтобы настроить вашу персональную
				летну и моментально узнавать о новых публикациях и обсуждениях
			</p>
		</div>
	</div>

	<div class="row">
		<div class="col">
			<ul class="view-switcher">
				<li class:selected={mode === 'views'}>
					<a href="#popular">Популярные</a>
				</li>
				<li class:selected={mode === 'shouts'}>
					<a href="#active">Активные</a>
				</li>
				<li class:selected={mode === 'alphabet'}>
					<a href="#alphabet">По алфавиту</a>
				</li>
			</ul>

			{#if mode === 'alphabet'}
				{#each sortedKeys as letter}
					<div class="group">
						<h2>{letter}</h2>

						<div class="container">
							<div class="row">
								{#each topicsGroupedByAlphabet[letter] as topic}
									<div class="topic col-3">
										<div class="topic-title">
											<a href="/topic/{topic.slug}">{topic.title}</a>
										</div>
									</div>
								{/each}
							</div>
						</div>
					</div>
				{/each}
			{:else}
				<div class="stats">
					{#each topics as topic}
						<TopicCard {topic} compact={false} subscribed={subscribedList && subscribedList.includes(topic.slug)} />
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>

<style lang="scss">
	.view-switcher {
		font-weight: bold;
		list-style: none;
		margin: 0 0 1.5em;
		padding: 0;

		li {
			display: inline-block;
			margin-right: 1em;
		}

		a {
			border-bottom: 2px solid #fff;
			color: #696969;
		}

		.selected {
			a {
				border-color: #000;
				color: #000;
				cursor: default;
			}
		}
	}

	.group {
		font-weight: bold;
		margin-bottom: 9.6rem;

		h2 {
			margin-bottom: 3.2rem;
			text-transform: capitalize;
		}

		.container {
			margin-left: $grid-gutter-width;
			padding-right: $container-padding-x;
			width: auto;
		}
	}
</style>
