// src/components/Editor/P2P.tsx
import { Show, createSignal, onMount } from 'solid-js'
import { IndexeddbPersistence } from 'y-indexeddb'
import { Awareness } from 'y-protocols/awareness'
import { WebrtcProvider } from 'y-webrtc'
import { XmlFragment, logUpdate } from 'yjs'

let p2p

export default (props) => {
  const [loading, setLoading] = createSignal()
  const [swarm, setSwarm] = createSignal('TEST') // FIXME

  onMount(() => {
    // TODO: generate room name
    setSwarm(`discours-fake-room-${Date.now()}`)
    console.log(`p2p: room is ${swarm()}`)

    p2p = new WebrtcProvider(swarm(), props.ydoc, {
      awareness: new Awareness(props.ydoc),
      filterBcConns: true,
      maxConns: 33,
      signaling: [
        // 'wss://signaling.discours.io',
        // 'wss://stun.l.google.com:19302',
        'wss://y-webrtc-signaling-eu.herokuapp.com',
        'wss://signaling.yjs.dev'
      ],
      peerOpts: {},
      password: ''
    })
    console.log('p2p: webrtc provider initialized')

    // init db
    const db = new IndexeddbPersistence(swarm(), props.ydoc)

    console.log('p2p: indexed db persistence connected')
    // connect p2p
    p2p.connect()
    props.onConnected(p2p)
    console.log('p2p: connected')
    // sync db
    db.on('synced', () => {
      const up = db.doc.getXmlFragment(`${swarm()}-body`)

      if (props.body !== up && up.length > 0) {
        body = up
        console.log('p2p: body updated')
      }

      setLoading(false)
    })
    p2p.doc.on('update', logUpdate)

    const remote = props.ydoc.getXmlFragment(`${swarm()}-body`)
    const local = props.body === '' ? new XmlFragment() : props.body

    if (remote === local) {
      console.log('p2p: no conflict to solve')
      body = remote
    } else {
      // TODO: implement conflict solving logix
      // если ты редактор - правишь как обычно
      // если ты не редактор - все правки становятся предложениями (proposal)
      console.log('p2p: conflict solving is not implemented yet')
    }
  })

  return (
    <Show when={p2p?.roomName && !loading()}>
      <small class='room'>{p2p.roomName}</small>
    </Show>
  )
}

// src/components/DiscoursEditor/P2P.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import {
		db,
		body,
		loading,
		ydoc,
		room,
		p2p,
		webrtc
	} from '../../stores/editor'
	import * as Y from 'yjs'
	import { WebrtcProvider } from 'y-webrtc'
	import { IndexeddbPersistence } from 'y-indexeddb'

	export let password: string

	const dbSynced = () => {
		const up = $db.doc.getXmlFragment($room + '-body')
		if ($body !== up && up.length > 0) {
			$body = up
			console.log('p2p: body updated')
		}
		$loading = false
	}

	const p2pDocUpdate = (update) => {
		$loading = true
		console.log('p2p: updating the doc')
		Y.logUpdate(update)
		$loading = false
	}

	onMount(() => {
		// TODO: generate room name from window.location
		$room =
			window.location.hostname +
			(window.location.pathname.length === 1 ? '' : window.location.pathname)
		console.log('p2p: room is ' + $room)
		// check if there is a pre-configured password
		if (password) $webrtc.password = password
		// init p2p provider
		$p2p = new WebrtcProvider($room, $ydoc, $webrtc)
		console.log('p2p: webrtc provider initialized')
		// init db
		$db = new IndexeddbPersistence($room, $ydoc)
		console.log('p2p: indexed db persistence connected')
		// connect p2p
		$p2p.connect()
		console.log('p2p: connected')
		// sync db
		$db.on('synced', dbSynced)
		$p2p.doc.on('update', p2pDocUpdate)
	})
</script>

{#if $p2p && $p2p.room}
	<small class="p-1 rounded border border-gray-400 room">
		{$p2p.roomName}
	</small>
{/if}

<style>
	.room {
		position: fixed;
		bottom: 0;
		background-color: plum;
		color: white;
		text-shadow: 1px 1px rebeccapurple;
	}
</style>
