// src/lib/components/DiscoursEditor/Editor.svelte
<script lang="ts">
  import './custom.css'

  import { keymap } from 'prosemirror-keymap'
  import { schema } from 'prosemirror-markdown'
  import { EditorState } from 'prosemirror-state'
  import { EditorView } from 'prosemirror-view'
  import { onDestroy, onMount } from 'svelte'
  import { fade } from 'svelte/transition'
  import {
    redo,
    undo,
    yCursorPlugin,
    ySyncPlugin,
    yUndoPlugin
  } from 'y-prosemirror'
  import { WebrtcProvider } from 'y-webrtc'
  import type { XmlFragment } from 'yjs'

  import { p2p as conn, room, webrtc, ydoc } from '$lib/stores/editor'
  import P2PConnect from './P2P.svelte'
  import { setup } from './setup'

  export let body: XmlFragment
  export let collab: boolean
  let element: HTMLDivElement = undefined
  let state: EditorState = undefined
  let plugins = []
  let view: EditorView = undefined

  $: if (collab) {
    console.log('editor: p2p collab mode')
    $conn = new WebrtcProvider($room, $ydoc, $webrtc)
  }

  $: if ($conn && $conn.awareness) {
    console.log('p2p: webrtc provider initialized')
    plugins = [
      ySyncPlugin(body),
      yCursorPlugin($conn.awareness),
      yUndoPlugin(),
      keymap({
        'Mod-z': undo,
        'Mod-y': redo,
        'Mod-Shift-z': redo
      })
    ].concat(setup({ schema }))
    view.updateState(EditorState.create({ schema, plugins }))
  }

  onMount(() => {
    let doc
    if (!collab) {
      doc = body.doc
      plugins = [
        keymap({
          'Mod-z': undo,
          'Mod-y': redo,
          'Mod-Shift-z': redo
        })
      ].concat(setup({ schema }))
    }
    state = EditorState.create(
      collab ? { schema, plugins } : { schema, plugins, doc }
    )
    view = new EditorView(element, { state })
    view.focus()
    document.querySelector('.ProseMirror-menubar').setAttribute('style', '')
  })

  onDestroy(() => view && view.destroy())
</script>

{#if collab}<P2PConnect password={$webrtc.password} />{/if}
<div class="editor" transition:fade bind:this={element} />

<style>
  .editor {
    justify-content: left;
    align-items: left;
  }
</style>

// src/components/Editor/index.tsx
import './custom.css'
import { keymap } from 'prosemirror-keymap'
import { schema } from 'prosemirror-markdown'
import { EditorState } from 'prosemirror-state'
import { EditorView } from 'prosemirror-view'
import { Show, createSignal, onCleanup, onMount } from 'solid-js'
import { Doc } from 'yjs'
import { redo, undo, yCursorPlugin, ySyncPlugin, yUndoPlugin } from 'y-prosemirror'
import { setup } from './setup'
import P2P from './P2P'

let element: HTMLDivElement
let state: EditorState
let view: EditorView

export default (props) => {
  const [ydoc, setYdoc] = createSignal(new Doc())
  const [plugins, setPlugins] = createSignal(
    [
      keymap({
        'Mod-z': undo,
        'Mod-y': redo,
        'Mod-Shift-z': redo
      })
    ].concat(setup({ schema }))
  )

  onMount(() => {
    state = EditorState.create({ schema, plugins: plugins(), doc: props.body.doc })
    view = new EditorView(element, { state })
    view.focus()
    document.querySelector('.ProseMirror-menubar').setAttribute('style', '')
  })

  onCleanup(() => view && view.destroy())

  const onConnected = async (conn) => {
    setPlugins([ySyncPlugin(props.body), yCursorPlugin(conn.awareness), yUndoPlugin(), ...plugins()])
    view.updateState(EditorState.create({ schema, plugins: plugins() }))
  }

  const submit = () => {
    // TODO: some button to trig article update
    props.onSubmit()
  }

  return (
    <>
      <Show when={props.collab}>
        <P2P body={props.body} ydoc={ydoc()} onConnected={onConnected} />
      </Show>
      <div class='editor' ref={element}></div>
    </>
  )
}
